services:
  web:
    build: .
    command: gunicorn config.asgi:application --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker --workers 4
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
    restart: always

  bot:
    build: .
    command: python manage.py runbot
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
      - persistence_pickle:/app/bot/data
    stop_grace_period: 25s
    restart: always

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
    restart: always
    depends_on:
      - redis
      - web

volumes:
  sqlite_data:
  persistence_pickle:
  redis_data:
