# Generated by Django 6.0.3 on 2026-03-24 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('data', models.JSONField(default=dict)),
                ('state', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.DecimalField(decimal_places=2, default=90.0, max_digits=10, verbose_name='Текущий курс USD')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Курс валют',
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_base_cost', models.DecimalField(decimal_places=2, default=1.35, max_digits=10, verbose_name='Базовая цена одной звезды')),
                ('usd_base_rate', models.DecimalField(decimal_places=2, default=80.0, max_digits=10, verbose_name='Базовый курс USD')),
                ('is_use_usd_rate', models.BooleanField(default=False, verbose_name='Учитывать курс доллара?')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Технический перерыв')),
            ],
            options={
                'verbose_name': 'Глобальные настройки',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название системы')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Комиссия (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Метод оплаты',
                'verbose_name_plural': 'Методы оплаты',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_fiat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('amount_stars', models.IntegerField(verbose_name='Количество звезд')),
                ('status', models.CharField(choices=[('PENDING', 'ОЖИДАЕТ'), ('SUCCESS', 'УСПЕШНО'), ('FAILED', 'ОШИБКА')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('telegram_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.telegramuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
            },
        ),
        migrations.CreateModel(
            name='TransactionMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PURCHASE', 'Покупка')], max_length=50, verbose_name='Тип')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Способ оплаты')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные (JSON)')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_info', to='core.transaction', verbose_name='Транзакция')),
            ],
            options={
                'verbose_name': 'Метаданные транзакции',
                'verbose_name_plural': 'Метаданные транзакций',
            },
        ),
    ]
