# Generated by Django 6.0.3 on 2026-02-26 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProfit',
            fields=[
            ],
            options={
                'verbose_name': 'Прибыль по месяцам',
                'verbose_name_plural': 'Прибыль по месяцам',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.transaction',),
        ),
    ]
