# Generated by Django 6.0.3 on 2026-03-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_monthlyprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='target_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='telegram_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.telegramuser', verbose_name='Покупатель'),
        ),
    ]
