# Generated by Django 6.0.3 on 2026-05-23 15:22

import core.domain.enums
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def create_default_records(apps, schema_editor):
    paymentapi = apps.get_model('core', 'paymentapi')
    _ = paymentapi.objects.create(name="Platega")


def reverse_default_records(apps, schema_editor):
    # Код для отката миграции
    paymentapi = apps.get_model('core', 'paymentapi')
    _ = paymentapi.objects.filter(name="Platega").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAPI',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название API платёжных систем')),
            ],
            options={
                'verbose_name': 'API платёжных систем',
                'verbose_name_plural': 'API платёжных систем',
            },
        ),
        migrations.RunPython(create_default_records, reverse_default_records),
        migrations.AddField(
            model_name='paymentmethod',
            name='external_id',
            field=models.CharField(default=-1, help_text='ID из внешнего API; Может быть числом или строкой', max_length=255, verbose_name='ID метода оплаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='star_base_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.35'), max_digits=10, verbose_name='Базовая цена одной звезды'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название метода оплаты'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(help_text='Это ID из внешнего API', primary_key=True, serialize=False, verbose_name='ID платежа'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ОЖИДАЕТ'), ('SUCCESS', 'УСПЕШНО'), ('CANCELLED', 'ОТМЕНЕНО'), ('FAILED', 'ОШИБКА')], default=core.domain.enums.TransactionStatus['PENDING'], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_username',
            field=models.CharField(blank=True, default='Себе', max_length=255, verbose_name='Кому'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('id', 'telegram_user'), name='unique_user_transaction_id'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='api',
            field=models.ForeignKey(default='Platega', on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='core.paymentapi', verbose_name='API платёжных систем'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('api', 'name'), name='unique_api_method_name'),
        ),
    ]
