# Generated by Django 6.0.3 on 2026-05-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rework_payments_optional_target_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Истекает'),
        ),
    ]
