# Generated by Django 6.0.3 on 2026-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_expires_at_to_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(help_text='Отображается в боте', max_length=50, verbose_name='Название метода оплаты'),
        ),
    ]
