# Generated by Django 6.0.3 on 2026-05-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_help_text_to_paymentmethod_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(blank=True, help_text='Должен обновляться автоматически во время работы бота')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Токен для FragmentAPI',
            },
        ),
    ]
