# Generated by Django 6.0.3 on 2026-06-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_fragmentapi_for_token_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='fragmentapi',
            name='token',
            field=models.TextField(blank=True, help_text='Можно получить в Dashboard на fragment-api.com/dashboard'),
        ),
    ]
