# Generated by Django 6.0.3 on 2026-07-09 16:47

import core.domain.enums
import core.integrations.fragment.enums
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_updated_at_to_globalsettings_and_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FragmentTransaction',
            fields=[
                ('fragment_id', models.UUIDField(primary_key=True, serialize=False, verbose_name='ID Fragment')),
                ('id_from_payment_api', models.UUIDField(verbose_name='ID из платёжного API')),
                ('status', models.CharField(choices=[('CREATED', 'CREATED'), ('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('BLOCKCHAIN_SENT', 'BLOCKCHAIN_SENT')], default=core.integrations.fragment.enums.FragmentStatus['CREATED'], max_length=40, verbose_name='Статус FRAGMENT')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Транзакции Fragment',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Только название; регистр учитывается', max_length=50, verbose_name='Промокод')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Указывается в %, например, 5.00 (не 0.05)', max_digits=5, verbose_name='Скидка %')),
                ('usage_account', models.BigIntegerField(blank=True, help_text='Если пусто - без ограничений', null=True, verbose_name='На аккаунт')),
                ('usage_global', models.BigIntegerField(blank=True, help_text='Если пусто - без ограничений', null=True, verbose_name='Всего')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_user_transaction_id',
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='promo_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата активации промокода'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='message_id',
            field=models.IntegerField(blank=True, default=-1, help_text='Нужно для вебхука', verbose_name='ID сообщения заказа'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pay_url',
            field=models.CharField(default='dummy.pay.link', help_text='Приходит из платёжной системы', max_length=255, verbose_name='URL оплаты'),
        ),
        migrations.AddField(
            model_name='transactionmetadata',
            name='promo_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Указывается в %, например, 5.00 (не 0.05)', max_digits=5, null=True, verbose_name='Скидка промокода %'),
        ),
        migrations.AddField(
            model_name='transactionmetadata',
            name='promo_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID промокода'),
        ),
        migrations.AddField(
            model_name='transactionmetadata',
            name='promo_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя промокода'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активен?'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ОЖИДАЕТ'), ('PROCESSING', 'В ПРОЦЕССЕ'), ('SENDING', 'В ОТПРАВКЕ'), ('SEND_CREATED', 'ОТПРАВЛЕНО'), ('IN_DOUBT', 'ПОД СОМНЕНИЕМ'), ('CHARGEBACKED', 'ВОЗВРАТ'), ('SUCCESS', 'УСПЕШНО'), ('CANCELLED', 'ОТМЕНЕНО'), ('FAILED', 'ОШИБКА')], default=core.domain.enums.TransactionStatus['PENDING'], max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='active_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_users', to='core.promocode', verbose_name='Актив. промокод'),
        ),
    ]
