# Generated by Django 6.0.3 on 2026-07-09 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_promos_FG_txs_new_statuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_fiat',
            field=models.DecimalField(decimal_places=2, help_text='Без скидки', max_digits=10, verbose_name='Сумма'),
        ),
    ]
