# Generated by Django 6.0.3 on 2026-07-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_amount_fiat_help_text_without_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_fiat',
            field=models.DecimalField(decimal_places=2, help_text='Со скидкой (если есть)', max_digits=10, verbose_name='Сумма'),
        ),
    ]
