# Generated by Django 6.0.3 on 2026-07-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_amount_fiat_help_text_with_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_stars',
            field=models.IntegerField(verbose_name='Звёзды'),
        ),
    ]
