# Generated by Django 6.0.3 on 2026-07-24 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_amount_stars_shorten_help_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotState',
        ),
    ]
