# Generated by Django 6.0.3 on 2026-07-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_bot_state_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения (HTML)')),
                ('media', models.FileField(blank=True, null=True, upload_to='broadcasts/', verbose_name='Медиа (Фото/Видео)')),
                ('button_texts', models.JSONField(blank=True, null=True, verbose_name='Тексты кнопок (JSON)')),
                ('button_urls', models.JSONField(blank=True, null=True, verbose_name='URL кнопок (JSON)')),
                ('telegram_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='File ID в Telegram')),
                ('preview_sent', models.BooleanField(default=False, verbose_name='Предпросмотр отправлен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False, verbose_name='Рассылка завершена')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
