# Generated by Django 6.0.3 on 2026-07-30 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_broadcast_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fragmenttransaction',
            options={'verbose_name': 'Транзакция Fragment', 'verbose_name_plural': 'Транзакции Fragment'},
        ),
    ]
