# Generated by Django 6.0.3 on 2026-07-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_fix_plural_for_fragment_tx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='button_texts',
            field=models.JSONField(blank=True, help_text='Формат (текст обязательно в двойных кавычках): null или список со списками названий, например, [["Строка1Столбец1", "Строка1Столбец2"], ["Строка2Столбец1"]]', null=True, verbose_name='Тексты кнопок (JSON)'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='button_urls',
            field=models.JSONField(blank=True, help_text='Формат такой же, как у текста кнопок (ссылки тоже должны быть в двойных кавычках)', null=True, verbose_name='URL кнопок (JSON)'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='preview_sent',
            field=models.BooleanField(default=False, help_text='Для массовой рассылки обязательно сначала отослать предпросмотр для кэширования файла', verbose_name='Предпросмотр отправлен'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='text',
            field=models.TextField(help_text='Для форматирования используется разметка HTML', verbose_name='Текст сообщения'),
        ),
    ]
