# Generated by Django 6.0.3 on 2026-07-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_help_texts_to_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast',
            name='name',
            field=models.CharField(blank=True, help_text='Необязательно к заполнению', max_length=50, verbose_name='Название рассылки'),
        ),
    ]
