# Generated by Django 6.0.3 on 2026-08-01 10:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_name_to_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, help_text='Пользователь неактивен, если у бота нет к нему доступа', verbose_name='Активный пользователь?'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Например, 1.00% (не 0.01)', max_digits=5, verbose_name='Комиссия %'),
        ),
    ]
