class UserRepository:
    def create_telegram_user(self, telegram_id, username):
        ...

    def get_by_telegram_id(self, telegram_id):
        ...

    def get_by_username(self, username):
        ...

    def get_many_by_date_period(self):
        ...

    def delete_user(self, user):
        ...
